version: 2.1

aliases:
  - &container_config
    executor: node-executor

executors:
  node-executor:
    docker:
      - image: circleci/node:lts-buster-browsers-legacy

jobs:
  Dependencies:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: log-directory
          command: ls -d */

  Security:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Audit Dependencies
          command: npm audit

  Quality:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Lint Code
          command: npm run lint

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - Dependencies
      - Security:
          requires:
            - Dependencies
      - Quality:
          requires:
            - Dependencies
